package com.example.budgetx.data

import androidx.room.Entity
import androidx.room.PrimaryKey

// This tells Room that this class defines a database table
@Entity(tableName = "expense_table")
data class Expense(
    // Every entry needs a unique ID so the database can find it
    @PrimaryKey(autoGenerated = true) val id: Int = 0,

    val amount: Double,       // Required: Specify amount
    val date: String,         // Required: Specify date
    val startTime: String,    // Required: Specify start time
    val endTime: String,      // Required: Specify end time
    val description: String,   // Required: Specify description
    val category: String,      // Required: Specify category

    // This stores the location of the photo on the phone
    val photoPath: String? = null
)